# Generated by Django 6.0.4 on 2026-05-08 15:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField()),
                ('ingredients', wagtail.fields.RichTextField()),
                ('method', wagtail.fields.RichTextField()),
                ('origin', models.CharField(max_length=500)),
                ('nutrition', wagtail.fields.RichTextField()),
                ('disclaimer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
