# Generated by Django 6.0.4 on 2026-05-12 07:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='cook_time',
            field=models.IntegerField(blank=True, help_text='Minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='prep_time',
            field=models.IntegerField(blank=True, help_text='Minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='ingredients',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='method',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
